name: Foodborne Outbreak nightly update

on:
  push:
    branches:
      - main
  schedule:
    - cron: '45 10 * * *'
  workflow_dispatch:

jobs:
  scrape-outbreaks:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Write access is needed to push changes back to the repository
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@61cb8a9741eeb8a550a1b8544337180c0fc8476b # v7.2.0
        with:
          version: 'latest'

      - name: Install Playwright browsers
        run: |
          uv run playwright install --with-deps chromium

      # - name: Running scrape script on FDA
      #   continue-on-error: true # FDA blocks Github action IPs and re-routes traffic.
      #   run: |
      #     uv run python main.py --fda

      - name: Running scrape script on CDC
        continue-on-error: true # If CDC is down, we don't want the whole job to fail.
        run: |
          uv run python main.py --cdc

      - name: Combine both FDA and CDC sources
        continue-on-error: true # If either source failed, this may not work properly
        run: |
          uv run python main.py --combine

      - name: Summarize using README
        run: |
          uv run python generate_stats.py

      - name: Commit and push changes
        if: github.ref == 'refs/heads/main'
        run: |
          git status
          git config --local user.email "noreply@github.com"
          git config --local user.name "github-actions[bot]"
          git add data/raw/
          git add README.md
          if ! git diff-index --quiet HEAD; then
            git commit -m "Nightly update of raw foodborne outbreak changes - $(date +'%Y-%m-%d')"
            git push -u origin main
          fi
